//
//  LibraryView.swift
//  ChatAI
//
//  Shows a simple grid of images from the user's Photos library so users can find the images generated by the app (saved via "Save to Photos").
//

import SwiftUI
import Photos
import PhotosUI
import UIKit

struct LibraryView: View {
    /// Optional callback to return a selected image to the caller as an attachment
    var onPick: ((Data, String) -> Void)? = nil
    @Environment(\.dismiss) private var dismiss
    @StateObject private var vm = LibraryViewModel()
    @State private var selectedAsset: PHAsset? = nil
    @State private var showFullScreen = false

    private let columns = [
        GridItem(.flexible(), spacing: 8),
        GridItem(.flexible(), spacing: 8),
        GridItem(.flexible(), spacing: 8)
    ]

    var body: some View {
        ZStack {
            Color.black.ignoresSafeArea()
            VStack(spacing: 0) {
                // Title bar
                HStack {
                    Text("Library")
                        .font(.headline)
                        .foregroundColor(.white)
                    Spacer()
                    Button(action: { vm.requestAuthorization() }) {
                        Image(systemName: "arrow.clockwise")
                            .foregroundColor(.white)
                    }
                }
                .padding(.horizontal, 16)
                .padding(.vertical, 10)

                content
            }
        }
        .onAppear { vm.load() }
        .sheet(isPresented: $showFullScreen) {
            if let asset = selectedAsset {
                FullscreenAssetView(asset: asset)
                    .ignoresSafeArea()
            }
        }
        .preferredColorScheme(.dark)
    }

    @ViewBuilder
    private var content: some View {
        switch vm.state {
        case .loading:
            ProgressView("Loading…").tint(.white).padding()
        case .denied:
            VStack(spacing: 12) {
                Text("Photos access is required to show your generated images.")
                    .foregroundColor(.white)
                    .multilineTextAlignment(.center)
                Button("Open Settings") { PHPhotoLibrary.open() }
                    .buttonStyle(.borderedProminent)
            }
            .padding()
        case .empty:
            Text("No photos found.")
                .foregroundColor(.white.opacity(0.8))
                .padding()
        case .ready:
            ScrollView {
                LazyVGrid(columns: columns, spacing: 8) {
                    ForEach(vm.assets, id: \.localIdentifier) { asset in
                        AssetGridCell(asset: asset)
                            .onTapGesture {
                                if let onPick {
                                    // Request full-size data and return to caller as attachment
                                    requestData(for: asset) { data in
                                        if let data {
                                            onPick(data, "image/jpeg")
                                            dismiss()
                                        }
                                    }
                                } else {
                                    selectedAsset = asset
                                    showFullScreen = true
                                }
                            }
                    }
                }
                .padding(8)
            }
        }
    }

    private func requestData(for asset: PHAsset, completion: @escaping (Data?) -> Void) {
        let options = PHImageRequestOptions()
        options.isSynchronous = false
        options.deliveryMode = .highQualityFormat
        options.resizeMode = .none
        PHImageManager.default().requestImageDataAndOrientation(for: asset, options: options) { data, _, _, _ in
            completion(data)
        }
    }
}

// MARK: - ViewModel
final class LibraryViewModel: ObservableObject {
    enum State { case loading, denied, empty, ready }
    @Published var state: State = .loading
    @Published var assets: [PHAsset] = []

    func requestAuthorization() {
        if #available(iOS 14, *) {
            PHPhotoLibrary.requestAuthorization(for: .readWrite) { _ in
                DispatchQueue.main.async { self.load() }
            }
        } else {
            PHPhotoLibrary.requestAuthorization { _ in
                DispatchQueue.main.async { self.load() }
            }
        }
    }

    func load() {
        let status: PHAuthorizationStatus
        if #available(iOS 14, *) { status = PHPhotoLibrary.authorizationStatus(for: .readWrite) } else { status = PHPhotoLibrary.authorizationStatus() }
        guard status == .authorized || status == .limited else {
            state = .denied
            return
        }
        DispatchQueue.global(qos: .userInitiated).async {
            let fetchOptions = PHFetchOptions()
            fetchOptions.sortDescriptors = [NSSortDescriptor(key: "creationDate", ascending: false)]
            // Fetch only images
            fetchOptions.predicate = NSPredicate(format: "mediaType == %d", PHAssetMediaType.image.rawValue)
            let result = PHAsset.fetchAssets(with: .image, options: fetchOptions)
            var items: [PHAsset] = []
            result.enumerateObjects { asset, _, _ in items.append(asset) }
            DispatchQueue.main.async {
                self.assets = items
                self.state = items.isEmpty ? .empty : .ready
            }
        }
    }
}

// MARK: - Grid Cell
private struct AssetGridCell: View {
    let asset: PHAsset
    @State private var image: UIImage? = nil

    var body: some View {
        ZStack {
            if let img = image {
                Image(uiImage: img)
                    .resizable()
                    .scaledToFill()
            } else {
                Color.white.opacity(0.08)
                ProgressView().tint(.white)
            }
        }
        .frame(height: 110)
        .clipped()
        .clipShape(RoundedRectangle(cornerRadius: 10))
        .onAppear { requestThumbnail() }
    }

    private func requestThumbnail() {
        let manager = PHImageManager.default()
        let options = PHImageRequestOptions()
        options.isSynchronous = false
        options.deliveryMode = .opportunistic
        options.resizeMode = .fast
        manager.requestImage(for: asset, targetSize: CGSize(width: 220, height: 220), contentMode: .aspectFill, options: options) { img, _ in
            self.image = img
        }
    }
}

// MARK: - Fullscreen viewer
private struct FullscreenAssetView: View {
    let asset: PHAsset
    @Environment(\.dismiss) private var dismiss
    @State private var image: UIImage? = nil

    var body: some View {
        ZStack {
            Color.black.ignoresSafeArea()
            if let img = image {
                Image(uiImage: img)
                    .resizable()
                    .scaledToFit()
                    .ignoresSafeArea()
            } else {
                ProgressView("Loading…").tint(.white)
            }
            VStack {
                HStack {
                    Button(action: { dismiss() }) {
                        Image(systemName: "xmark.circle.fill").foregroundColor(.white).font(.title2)
                    }
                    Spacer()
                }
                .padding()
                Spacer()
            }
        }
        .onAppear { requestFullSize() }
    }

    private func requestFullSize() {
        let manager = PHImageManager.default()
        let options = PHImageRequestOptions()
        options.isSynchronous = false
        options.deliveryMode = .highQualityFormat
        options.resizeMode = .none
        manager.requestImageDataAndOrientation(for: asset, options: options) { data, _, _, _ in
            if let data, let img = UIImage(data: data) {
                self.image = img
            }
        }
    }
}

extension PHPhotoLibrary {
    static func open() {
        guard let url = URL(string: UIApplication.openSettingsURLString) else { return }
        DispatchQueue.main.async { UIApplication.shared.open(url) }
    }
}
